name: sidequests

services:
  web:
    container_name: "sidequests-web"
    build: .
    secrets:
      - nuxt_database_url
    environment:
      NUXT_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      NUXT_SESSION_PASSWORD: ${NUXT_SESSION_PASSWORD}
      NUXT_SITE_URL: ${NUXT_SITE_URL}
    ports:
      - "3000:3000"
    networks:
      - sidequests
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    container_name: "sidequests-db"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    networks:
      - sidequests
    volumes:
      - pgdata:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - sidequests

networks:
  sidequests:
    driver: bridge

secrets:
  nuxt_database_url:
    environment: NUXT_DATABASE_URL

volumes:
  pgdata: