services:
  web:
    build: .
    env_file: ".env"
    ports:
      - "3000:3000"
    networks:
      - sidequests
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    networks:
      - sidequests

networks:
    sidequests:
      driver: bridge