name: sidequests

services:
  #  mariadb:
  #    image: mariadb:latest
  #    restart: always
  #    env_file:
  #      - .env
  #    ports:
  #      - "3306:3306"
  #    volumes:
  #      - db-data:/db
  #    networks:
  #      - mariadb_network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

#  web:
#    build: .
#    command: pnpm run dev
#    ports:
#      - "3000:3000"
#    develop:
#      watch:
#        - action: sync
#          path: .
#          target: ./app
#          initial_sync: true
#        - action: rebuild
#          path: package.json

volumes:
  pgdata:
